[build]
  command = "npm run build"
  publish = "dist"

# Form success redirect
[[redirects]]
  from = "/contact/"
  to = "/success/"
  status = 200
  query = {nf = ":nf"}  # Only redirect after form submission

# www redirect
[[redirects]]
  from = "https://www.ymboxs.com/*"
  to = "https://ymboxs.com/:splat"
  status = 301
  force = true
