backend:
  name: github
  repo: ARIEZY997/yuanmei-printing
  branch: master
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: auth
  client_id: Ov23lihQkBP0O5pz8LBj
media_folder: public/images
public_folder: /images
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: seo
    label: Page TDK Settings
    files:
      - name: seodata
        label: All Pages SEO
        file: src/data/seo.json
        fields:
          - name: home
            label: Homepage
            widget: object
            fields:
              - { name: title, label: "Title (T)", widget: string }
              - { name: description, label: "Description (D)", widget: text }
          - name: about
            label: About Page
            widget: object
            fields:
              - { name: title, label: "Title (T)", widget: string }
              - { name: description, label: "Description (D)", widget: text }
          - name: products
            label: Products Page
            widget: object
            fields:
              - { name: title, label: "Title (T)", widget: string }
              - { name: description, label: "Description (D)", widget: text }
          - name: contact
            label: Contact Page
            widget: object
            fields:
              - { name: title, label: "Title (T)", widget: string }
              - { name: description, label: "Description (D)", widget: text }
